### ISSUE TITLE
android.support error after add Library gradle and sync

### ISSUE THREAD

**Issue by kasterlod** [fabian7593/MagicalCamera#10]
The following classes could not be instantiated:
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- android.support.design.widget.FloatingActionButton (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)

Hello
There is some errors in xml after gradle sync with library v1

**Comment by fabian7593** [comment]
Hello please make sure that the VERSION for AppCompat Library and the Design Support Library is the same. This is mostly an internal dependency conflict, not for the library...

like this (in dependencies)
compile 'com.android.support:appcompat-v7:24.2.1'
compile 'com.android.support:design:24.2.1'

Or try  with the version 22...
Thanks...

Not forgive to check like resolved :)
