### ISSUE TITLE
I am getting following error, please help how to sort it.

### ISSUE THREAD

**Issue by swappy350** [fabian7593/MagicalCamera#11]
11-14 14:25:06.498: E/AndroidRuntime(7487): java.lang.UnsatisfiedLinkError: Couldn't load MagicSDK from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.seu.magiccamera-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.seu.magiccamera-1, /vendor/lib, /system/lib]]]: findLibrary returned null

**Comment by fabian7593** [comment]
Hello @swappy350  the library name is MagicalCamera and the actual version is 4.8 ... your stack trace menction MagicSDK  and com.seu.magiccamera-1.apk" ... please use gradle to integrate the library in your project if you use android studio, or import the .jar in the project...
Please check if you use this library please.
