### ISSUE TITLE
Permissions in fragments [REQUEST]

### ISSUE THREAD

**Issue by cutiko** [fabian7593/MagicalCamera#14]
Greetings

Usually fragments will modularized blocks of logic. Taking a picture is a block of logic by itself. If it is, gallery or camera, getting the result, updating the UI, saving the photo locally and cloud, etc.

Dialog for permissions using the library method are displaying if are requested from a fragment:

```
permissionGranted.checkCameraPermission();
permissionGranted.checkReadExternalPermission();
permissionGranted.checkWriteExternalPermission();
```

The problem is onRequestPermissionsResult is never called in the fragment, but it does in the Activity.

Initially I thought this could be due some sort of device error, so try with others, including emulator and the behaviour was the same. This seems to be not mentioned in the [official docs](https://developer.android.com/training/permissions/requesting.html?hl=es) but I found a clue searching in [StackOverflow](http://stackoverflow.com/a/37854430/4017501).

It seems that asking permissions from a fragment is different than from an Activity.

Permissions feature is great, thanks for it, but if you could add a fragment version for the permissions it would help us a lot to write more robust code. Thanks.

**Comment by fabian7593** [comment]
I'm really amazed, because I test this in my device and its works. but maybe I need to test again.
Thanks for report the issue.

**Comment by cutiko** [comment]
It does work, the permissions are granted and the photo process work, take then save.

The problem is "onRequestPermissionsResult" is not called in the fragment. Figure if the goal.is to provide a flawless experience for the user. The user opens an Activity where takes the photo, and then the intent is automatically started. In the fragment there should be a validation for the device API lvl and permissions so the first time will ask for permissions and then in the onResult method the intent is executed. Next time there are permissions so the intent is started in the else of the validation.

**Comment by fabian7593** [comment]
I search about this issue @cutiko  and I implement a solution of this, but anything solved the problem, I dont know why, If you want  to help the library realize a commit not a pull request and in my account arrive  your work ;) ...
In this moment the solution is declare static variable of PermissionGranted in activity and pass this to the fragment.
