### ISSUE TITLE
Problem with Android >= 24

### ISSUE THREAD

**Issue by jaesga** [fabian7593/MagicalCamera#15]
Hi, I think this lib is not supporting Android 24 properly. 
I am getting this error:

> android.os.FileUriExposedException: file:///storage/emulated/0/... exposed 

Reference:
http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

Regards,

**Comment by fabian7593** [comment]
Hello, and thanks for report the issue @jaesga.
I can upload the new version with this fix in next week.

**Comment by TwinsOd** [comment]
i am get this error too.

**Comment by fabian7593** [comment]
@TwinsOd and @jaesga Do you use the compile 'com.frosquivel:magicalcamera:5.0.2' version?
I solved this in 5.0.2, please try again and tell me how did it go...

**Comment by TwinsOd** [comment]
I have used 4.8 version libs, now fix and all great working. Thank you!!!

**Comment by fabian7593** [comment]
@TwinsOd thanks for comment your opinion, I do close this issue :)
