### ISSUE TITLE
way to take multi photo

### ISSUE THREAD

**Issue by ardakaplan** [fabian7593/MagicalCamera#32]
This isn't issue but i dont know where to ask question ?=)

Is this possible to take multi picture. Right now,
 `magicalCamera.takeFragmentPhoto(this);`
open app and take one picture and than show preview screen. I dont want preview screen and want to tahe multi picture at over and over

By the way, thanks for your project =)

**Comment by fabian7593** [comment]
Not with magical camera, because I dont use the Camera api2... I use the intent of device specifically and this intent already has a default action.
You need to implement Camera api 2 manuallity for realize this.
