### ISSUE TITLE
Can't take a picture on Android 6.0 or higher

### ISSUE THREAD

**Issue by geeflizz** [fabian7593/MagicalCamera#39]
I can't open the camera and take a pic using magicalcamera. The code `magicalCamera.takePhoto();` doesn't work on the following devices:

- ZTE BLADE A510. Android 6.0;
- LG X power. Android 6.0;
- Xiaomi Redmi 4X. Android 7.0.

Saying "the code doesn't work" I mean it literally doesn't do anything. No crashes, no errors, no any reaction.

BUT it works perfectly on Oysters Pacific E. Android 6.0...I can't find the difference...

I'm using 5.0.2 version

**Comment by hangocanh2303** [comment]
<uses-permission android:name="android.permission.CAMERA" />

**Comment by fabian7593** [comment]
Can you test the play store magical camera app...
I dont know what happen, because the camera is the camera intent of android

**Comment by fabian7593** [comment]
https://github.com/fabian7593/MagicalCamera/issues/36#issuecomment-466699668
