### ISSUE TITLE
App close in android 7 and higher

### ISSUE THREAD

**Issue by jlmd0222** [fabian7593/MagicalCamera#40]
Hello. I get the following error when take a photo, I am using 5.0.5 version 

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.proyectosandroid.siti.magicalcamera/com.proyectosandroid.siti.magicalcamera.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference at android.app.ActivityThread.deliverResults(ActivityThread.java:4339)                                                                                           at android.app.ActivityThread.handleSendResult(ActivityThread.java:4382)                                                                                           at android.app.ActivityThread.-wrap19(Unknown Source:0)                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1654)                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)                                                                                           at android.os.Looper.loop(Looper.java:251)                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6563)                                                                                           at java.lang.reflect.Method.invoke(Native Method)                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)                                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference                                                                                           at com.frosquivel.magicalcamera.Utilities.PictureUtils.resizePhoto(PictureUtils.java:43)                                                                                           at com.frosquivel.magicalcamera.Functionallities.ActionPicture.onTakePhotoResult(ActionPicture.java:184)                                                                                           at com.frosquivel.magicalcamera.Functionallities.ActionPicture.resultPhoto(ActionPicture.java:203)                                                                                           at com.frosquivel.magicalcamera.MagicalCamera.resultPhoto(MagicalCamera.java:206)                                                                                           at com.proyectosandroid.siti.magicalcamera.MainActivity.onActivityResult(MainActivity.java:83)                                                                                           at android.app.Activity.dispatchActivityResult(Activity.java:7235)                                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:4335)

**Comment by fabian7593** [comment]
Yeah, thanks for report the issue, on this week I Fix and upload a new version...

**Comment by fabian7593** [comment]
https://github.com/fabian7593/MagicalCamera/issues/36#issuecomment-466699668
