### ISSUE TITLE
Error in activityonresult and Path or Bitmap is null

### ISSUE THREAD

**Issue by MikeMcflako** [fabian7593/MagicalCamera#44]
When i take a photo with Magical Camera i get a problem, if i use         magicalCamera.resultPhoto(requestCode, resultCode, data);
in activityonresult in fragment the app crashes, but when i use it in Activity is ok but
magicalCamera.getPhoto()
returns a null Bitmap
or this one
String path = magicalCamera.savePhotoInMemoryDevice(magicalCamera.getPhoto(),"myPhotoName","myDirectoryName", MagicalCamera.JPEG, true);
returns a null String
Could you help me with this problem?
Or teach me how to use this library with fragments?

**Comment by fabian7593** [comment]
https://github.com/fabian7593/MagicalCamera/issues/36#issuecomment-466699668
