### ISSUE TITLE
Multidex Problem

### ISSUE THREAD

**Issue by cutiko** [fabian7593/MagicalCamera#8]
Greetings

I have a multidex warning after upgrading to 3.0 but got fix by using the transitive property indicated for version 1.0.

```
compile('com.frosquivel:magicalcamera:3.0@aar') {
        transitive = false;
}
```

Not a problem, just leaving this here incase anyone else run on the same issue.

**Comment by fabian7593** [comment]
Hello @cutiko thanks for use magical camera and for report this issue and to give us the solution.
